---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 24554.
--- DateTime: 2023/9/14 22:42
---
--优惠卷id
local voucherId=ARGV[1]
--用户id
local userId=ARGV[2]
--订单id
local orderId=ARGV[3]
--库存key
local stockKey='seckill:stock:' .. voucherId
--订单key
local orderKey='seckill:order:' .. voucherId

if(tonumber(redis.call('get',stockKey))<=0) then
    --库存不足，返回1
    return 1
end

if(redis.call('sismember',orderKey,userId)==1) then
    --存在，重复下单,返回2
    return 2
end

--扣减库存，下单
redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)
--发送到消息队列
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0